name: "Test GitHub CI Matrix Feature"

on:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "${{ matrix.os }}--${{ matrix.version }}"
