name: "Test GitHub CI Matrix Feature"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # build:
  #   strategy:
  #     matrix:
  #       version: [10, 12, 14]
  #       os: [ubuntu-latest, windows-latest]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Echo
  #       run: echo "${{ matrix.os }}--${{ matrix.version }}"
  honk:
    # https://stackoverflow.com/a/68940067/1528210
    strategy:
      matrix:
        os:
          [
            { base: ubuntu, version: 20.04.5 },
            { base: ubuntu, version: 22.04.3 },
            { base: debian, version: 11 },
          ]
        # We use a rather new version of git for shallow, sparse clones to save CO2 emsissions.
        # Recommended reading:
        # GitHub blog "Get up to speed with partial clone and shallow clone "
        # url: https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
        gitversion: [2.3.2]
        # The list of CopperSpice version we want to support
        cs_releasetag: [cs-1.8.1]
        # The build platform is the one we use for running the compiler or cross compiler
        build_platform: [x86-64]
        # The target platform is the one where the artefacts will run
        target_platform: [x86-64, armhf, arm64]
        # The selected C and C++ compilers
        compiler: [{ c: gcc-11, cpp: g++-11 }]

        # The include feature is used to switch to cross-compilers using
        include:
          - compiler_postfix: { c: "", cpp: "" }
          - target_platform: armhf
            compiler_postfix:
              { c: -arm-linux-gnueabihf, cpp: -arm-linux-gnueabihf }
          - target_platform: arm64
            compiler_postfix: { c: -aarch64-linux-gnu, cpp: -aarch64-linux-gnu }
    runs-on: ubuntu-22.04
    steps:
      - name: Echo C++
        run: |
          echo "${{ matrix.os.base }}-${{ matrix.os.version }}__${{ matrix.target_platform }}__${{ matrix.cs_releasetag }}__git-${{ matrix.gitversion }}__${{ matrix.compiler.cpp }}${{ matrix.compiler_postfix.cpp }}"
          echo "${{ matrix.os.base }}-${{ matrix.os.version }}__${{ matrix.target_platform }}__${{ matrix.cs_releasetag }}__git-${{ matrix.gitversion }}__${{ matrix.compiler.c }}${{ matrix.compiler_postfix.c }}"
      - name: Conditional Run
        if: ${{ matrix.compiler_postfix.cpp != '' }}
        run: |-
          echo "Cross Compiler!"
      # - name: Clone Copperspice
      #   run:
      #     git clone --branch ${{ matrix.cs_releasetag }}
      #     --depth 1 https://github.com/copperspice/copperspice
      ## && git log

#
# TODO: check https://github.com/marketplace/actions/arm-runner
# https://wiki.debian.org/Multiarch/HOWTO

# List of possible Debian architectures
# Retrieved from https://wiki.debian.org/ArchitectureSpecificsMemo
# amd64, arc, arm64, armel, armhfm, i386m mips, mipsel, mips64el, powerpc, powerpcspe, ppc64, ppc64el, s390x, loong64

# i386	1762483
# all	776922
# powerpc	34420
# ia64	18224
# hppa	5985
# sparc	1293
# m68k	987
# alpha	824
# arm	45
# mips	14
# mipsel	6
# s390	3

# 'hf' means hard-float which indicates that the compiler and its underlying
# libraries are using hardware floating point instructions rather than a
# software implementation of floating point such as fixed point software
# implementations.
#  gcc-10-arm-linux-gnueabihf \
#  g++-10-arm-linux-gnueabihf
