name: "Test GitHub CI Matrix Feature"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # build:
  #   strategy:
  #     matrix:
  #       version: [10, 12, 14]
  #       os: [ubuntu-latest, windows-latest]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Echo
  #       run: echo "${{ matrix.os }}--${{ matrix.version }}"
  honk:
    # https://stackoverflow.com/a/68940067/1528210
    strategy:
      matrix:
        os:
          [
#            { base: ubuntu, version: 20.04.5 },
            { base: ubuntu, version: 22.04.3 },
#            { base: debian, version: 11 },
          ]
        gitversion: [2.3.2]
        cs_releasetag: [cs-1.8.1, cs-1.8.0]
        target_platform: [x86-64, armhf, arm64] 
#        compiler_postfix: [{ c: '', cpp: '' }]
        include:
          - compiler_c: gcc-10
            compiler_cpp: g++-10
          - target_platform: armhf  
            compiler_c: gcc-10-arm-linux-gnueabihf
            compiler_cpp: g++-10-arm-linux-gnueabihf
          - target_platform: arm64  
            compiler_c: gcc-10-aarch64-linux-gnu
            compiler_cpp: g++-10-aarch64-linux-gnu
          # - compiler: [{ c: gcc-10, cpp: g++-10 }]
          # - compiler: [{ c: gcc-10-arm-linux-gnueabihf, cpp: g++-10-arm-linux-gnueabihf }]          
          #   target_platform: armhf
            
          #   compiler_postfix: [{ c: '-arm-linux-gnueabihf', cpp: '-arm-linux-gnueabihf' }]
          # - target_platform: arm64
          #   compiler_postfix: [{ c: '-aarch64-linux-gnu', cpp: '-aarch64-linux-gnu' }]
    runs-on: ubuntu-22.04
    steps:
      - name: Echo C++
        run: 
          echo "${{ matrix.os.base }}-${{ matrix.os.version }}__${{ matrix.target_platform }}__${{ matrix.cs_releasetag }}__git-${{ matrix.gitversion }}__${{ matrix.compiler_cpp }}"
      - name: Echo C
        run:
          echo "${{ matrix.os.base }}-${{ matrix.os.version }}__${{ matrix.target_platform }}__${{ matrix.cs_releasetag }}__git-${{ matrix.gitversion }}__${{ matrix.compiler_c }}"
      # - name: Clone Copperspice
      #   run:
      #     git clone --branch ${{ matrix.cs_releasetag }}
      #     --depth 1 https://github.com/copperspice/copperspice
          ## && git log
#
# TODO: check https://github.com/marketplace/actions/arm-runner
# https://wiki.debian.org/Multiarch/HOWTO

# List of possible Debian architectures
# Retrieved from https://wiki.debian.org/ArchitectureSpecificsMemo
# amd64, arc, arm64, armel, armhfm, i386m mips, mipsel, mips64el, powerpc, powerpcspe, ppc64, ppc64el, s390x, loong64

# i386	1762483
# all	776922
# powerpc	34420
# ia64	18224
# hppa	5985
# sparc	1293
# m68k	987
# alpha	824
# arm	45
# mips	14
# mipsel	6
# s390	3

# 'hf' means hard-float which indicates that the compiler and its underlying
# libraries are using hardware floating point instructions rather than a
# software implementation of floating point such as fixed point software
# implementations.
#  gcc-10-arm-linux-gnueabihf \
#  g++-10-arm-linux-gnueabihf
